version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: letrero-led-web
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letrero-led.rule=Host(\`letrero.johandev.lat\`)"
      - "traefik.http.services.letrero-led.loadbalancer.server.port=80"
